layout:
  defaultGroup: custom
  groups:
    - name: content
      apps:
        - name: pages-app
        - name: dam
        - name: stories
        - name: tours
        - name: books-app
    - name: travel
      label: Travel
      apps:
        - name: tourGuides-app
        - name: tourOffices-app
        - name: tourVehicles-app
  rows:
    - name: one
      cssClass: editor
      groups:
        content: content
        marketing: marketing
        travel: travel
